os: linux
dist: xenial

services:
  - postgresql
  - xvfb

language: python 
python: "3.8"

addons:
  chrome: stable

install:
  - sudo apt install unzip
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis", ENV="DEVELOPMENT", TEST_ENV="TRAVIS_CI"

before_script:
  - wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
  - unzip -u chromedriver_linux64.zip -d $HOME/aanselmi/P8

script:
 - ./manage.py test --tag="product-quality"
